# SATLL_OBC_STM32H735VIT6
# -----------------------------------------------------------------------------

set(SATLL_OBC_STM32H735VIT6_VARIANT_PATH "${CMAKE_CURRENT_LIST_DIR}/../variants/SATLL_OBC
set(SATLL_OBC_STM32H735VIT6_MAXSIZE 2097152)
set(SATLL_OBC_STM32H735VIT6_MAXDATASIZE 524288)
set(SATLL_OBC_STM32H735VIT6_MCU cortex-m7)
set(SATLL_OBC_STM32H735VIT6_FPCONF "-")
add_library(SATLL_OBC_STM32H735VIT6 INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6 INTERFACE
  "SHELL:-DCORE_CM7 -DSTM32H753xx  "
  "SHELL:"
  "SHELL:"
  "SHELL:-mfpu=fpv4-sp-d16 -mfloat-abi=hard"
  -mcpu=${SATLL_OBC_STM32H735VIT6_MCU}
)
target_compile_definitions(SATLL_OBC_STM32H735VIT6 INTERFACE
  "STM32H7xx"
	"ARDUINO_SATLL_OBC_STM32H735VIT6"
	"BOARD_NAME=\"SATLL_OBC_STM32H735VIT6\""
	"BOARD_ID=SATLL_OBC_STM32H735VIT6"
	"VARIANT_H=\"variant_generic.h\""
)
target_include_directories(SATLL_OBC_STM32H735VIT6 INTERFACE
  ${CMAKE_CURRENT_LIST_DIR}/../system/STM32H7xx
  ${CMAKE_CURRENT_LIST_DIR}/../system/Drivers/STM32H7xx_HAL_Driver/Inc
  ${CMAKE_CURRENT_LIST_DIR}/../system/Drivers/STM32H7xx_HAL_Driver/Src
  ${CMAKE_CURRENT_LIST_DIR}/../system/Drivers/CMSIS/Device/ST/STM32H7xx/Include/
  ${CMAKE_CURRENT_LIST_DIR}/../system/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc/
  ${SATLL_OBC_STM32H735VIT6_VARIANT_PATH}
)

target_link_options(SATLL_OBC_STM32H735VIT6 INTERFACE
  "LINKER:--default-script=${SATLL_OBC_STM32H735VIT6_VARIANT_PATH}/ldscript.ld"
  "LINKER:--defsym=LD_FLASH_OFFSET=0x0"
	"LINKER:--defsym=LD_MAX_SIZE=2097152"
	"LINKER:--defsym=LD_MAX_DATA_SIZE=524288"
  "SHELL:-mfpu=fpv4-sp-d16 -mfloat-abi=hard"
  -mcpu=${SATLL_OBC_STM32H735VIT6_MCU}
)

add_library(SATLL_OBC_STM32H735VIT6_serial_disabled INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_serial_disabled INTERFACE
  "SHELL:"
)
add_library(SATLL_OBC_STM32H735VIT6_serial_generic INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_serial_generic INTERFACE
  "SHELL:-DHAL_UART_MODULE_ENABLED"
)
add_library(SATLL_OBC_STM32H735VIT6_serial_none INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_serial_none INTERFACE
  "SHELL:-DHAL_UART_MODULE_ENABLED -DHWSERIAL_NONE"
)
add_library(SATLL_OBC_STM32H735VIT6_usb_CDC INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_usb_CDC INTERFACE
  "SHELL:-DUSBCON  -DUSBD_VID=0x0483 -DUSBD_PID=0x5740 -DHAL_PCD_MODULE_ENABLED -DUSBD_USE_CDC -DDISABLE_GENERIC_SERIALUSB"
)
add_library(SATLL_OBC_STM32H735VIT6_usb_CDCgen INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_usb_CDCgen INTERFACE
  "SHELL:-DUSBCON  -DUSBD_VID=0x0483 -DUSBD_PID=0x5740 -DHAL_PCD_MODULE_ENABLED -DUSBD_USE_CDC"
)
add_library(SATLL_OBC_STM32H735VIT6_usb_HID INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_usb_HID INTERFACE
  "SHELL:-DUSBCON  -DUSBD_VID=0x0483 -DUSBD_PID=0x5740 -DHAL_PCD_MODULE_ENABLED -DUSBD_USE_HID_COMPOSITE"
)
add_library(SATLL_OBC_STM32H735VIT6_usb_none INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_usb_none INTERFACE
  "SHELL:"
)
add_library(SATLL_OBC_STM32H735VIT6_xusb_FS INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_xusb_FS INTERFACE
  "SHELL:"
)
add_library(SATLL_OBC_STM32H735VIT6_xusb_HS INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_xusb_HS INTERFACE
  "SHELL:-DUSE_USB_HS"
)
add_library(SATLL_OBC_STM32H735VIT6_xusb_HSFS INTERFACE)
target_compile_options(SATLL_OBC_STM32H735VIT6_xusb_HSFS INTERFACE
  "SHELL:-DUSE_USB_HS -DUSE_USB_HS_IN_FS"
)

# SATLL_ADCS_STM32H735VIT6
# -----------------------------------------------------------------------------

set(SATLL_ADCS_STM32H735VIT6_VARIANT_PATH "${CMAKE_CURRENT_LIST_DIR}/../variants/SATLL_ADCS
set(SATLL_ADCS_STM32H735VIT6_MAXSIZE 2097152)
set(SATLL_ADCS_STM32H735VIT6_MAXDATASIZE 524288)
set(SATLL_ADCS_STM32H735VIT6_MCU cortex-m7)
set(SATLL_ADCS_STM32H735VIT6_FPCONF "-")
add_library(SATLL_ADCS_STM32H735VIT6 INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6 INTERFACE
  "SHELL:-DCORE_CM7 -DSTM32H753xx  "
  "SHELL:"
  "SHELL:"
  "SHELL:-mfpu=fpv4-sp-d16 -mfloat-abi=hard"
  -mcpu=${SATLL_ADCS_STM32H735VIT6_MCU}
)
target_compile_definitions(SATLL_ADCS_STM32H735VIT6 INTERFACE
  "STM32H7xx"
	"ARDUINO_SATLL_ADCS_STM32H735VIT6"
	"BOARD_NAME=\"SATLL_ADCS_STM32H735VIT6\""
	"BOARD_ID=SATLL_ADCS_STM32H735VIT6"
	"VARIANT_H=\"variant_generic.h\""
)
target_include_directories(SATLL_ADCS_STM32H735VIT6 INTERFACE
  ${CMAKE_CURRENT_LIST_DIR}/../system/STM32H7xx
  ${CMAKE_CURRENT_LIST_DIR}/../system/Drivers/STM32H7xx_HAL_Driver/Inc
  ${CMAKE_CURRENT_LIST_DIR}/../system/Drivers/STM32H7xx_HAL_Driver/Src
  ${CMAKE_CURRENT_LIST_DIR}/../system/Drivers/CMSIS/Device/ST/STM32H7xx/Include/
  ${CMAKE_CURRENT_LIST_DIR}/../system/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc/
  ${SATLL_ADCS_STM32H735VIT6_VARIANT_PATH}
)

target_link_options(SATLL_ADCS_STM32H735VIT6 INTERFACE
  "LINKER:--default-script=${SATLL_ADCS_STM32H735VIT6_VARIANT_PATH}/ldscript.ld"
  "LINKER:--defsym=LD_FLASH_OFFSET=0x0"
	"LINKER:--defsym=LD_MAX_SIZE=2097152"
	"LINKER:--defsym=LD_MAX_DATA_SIZE=524288"
  "SHELL:-mfpu=fpv4-sp-d16 -mfloat-abi=hard"
  -mcpu=${SATLL_ADCS_STM32H735VIT6_MCU}
)

add_library(SATLL_ADCS_STM32H735VIT6_serial_disabled INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_serial_disabled INTERFACE
  "SHELL:"
)
add_library(SATLL_ADCS_STM32H735VIT6_serial_generic INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_serial_generic INTERFACE
  "SHELL:-DHAL_UART_MODULE_ENABLED"
)
add_library(SATLL_ADCS_STM32H735VIT6_serial_none INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_serial_none INTERFACE
  "SHELL:-DHAL_UART_MODULE_ENABLED -DHWSERIAL_NONE"
)
add_library(SATLL_ADCS_STM32H735VIT6_usb_CDC INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_usb_CDC INTERFACE
  "SHELL:-DUSBCON  -DUSBD_VID=0x0483 -DUSBD_PID=0x5740 -DHAL_PCD_MODULE_ENABLED -DUSBD_USE_CDC -DDISABLE_GENERIC_SERIALUSB"
)
add_library(SATLL_ADCS_STM32H735VIT6_usb_CDCgen INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_usb_CDCgen INTERFACE
  "SHELL:-DUSBCON  -DUSBD_VID=0x0483 -DUSBD_PID=0x5740 -DHAL_PCD_MODULE_ENABLED -DUSBD_USE_CDC"
)
add_library(SATLL_ADCS_STM32H735VIT6_usb_HID INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_usb_HID INTERFACE
  "SHELL:-DUSBCON  -DUSBD_VID=0x0483 -DUSBD_PID=0x5740 -DHAL_PCD_MODULE_ENABLED -DUSBD_USE_HID_COMPOSITE"
)
add_library(SATLL_ADCS_STM32H735VIT6_usb_none INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_usb_none INTERFACE
  "SHELL:"
)
add_library(SATLL_ADCS_STM32H735VIT6_xusb_FS INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_xusb_FS INTERFACE
  "SHELL:"
)
add_library(SATLL_ADCS_STM32H735VIT6_xusb_HS INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_xusb_HS INTERFACE
  "SHELL:-DUSE_USB_HS"
)
add_library(SATLL_ADCS_STM32H735VIT6_xusb_HSFS INTERFACE)
target_compile_options(SATLL_ADCS_STM32H735VIT6_xusb_HSFS INTERFACE
  "SHELL:-DUSE_USB_HS -DUSE_USB_HS_IN_FS"
)